new instance

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,39 +1,56 @@
 version: '3.8'
 
+networks:
+  bigdata:
+    driver: bridge
 services:
   data-downloader:
-      build: .
-      command: >
-        bash -c "
-          set -e; 
-          if [ ! -f /data/raw/olist_orders_dataset.csv ]; then
-            echo 'Olist dataset not found. Downloading from Kaggle...' &&
-            kaggle datasets download -d olistbr/brazilian-ecommerce -p /data/raw --unzip &&
-            echo 'Download and extraction complete.';
-          else
-            echo 'Olist dataset already exists. Skipping download.';
-          fi
-        "
-      volumes:
-        - ./data:/data
-        - ./.kaggle:/root/.kaggle
+    build: .
+    command: >
+      bash -c "
+        set -e; 
+        if [ ! -f /data/raw/olist_orders_dataset.csv ]; then
+          echo 'Olist dataset not found. Downloading from Kaggle...' &&
+          kaggle datasets download -d olistbr/brazilian-ecommerce -p /data/raw --unzip &&
+          echo 'Download and extraction complete.';
+        else
+          echo 'Olist dataset already exists. Skipping download.';
+        fi
+      "
+    volumes:
+      - ./data:/data
+      - ./.kaggle:/root/.kaggle
+    networks:
+      - bigdata
 
   spark-master:
     build: 
       context: .
       dockerfile: spark/Dockerfile
-    # image: apache/spark:3.5.1
     container_name: spark-master
-    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
+    # command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
+    command: >
+      /opt/spark/bin/spark-class
+      -Dspark.master.rest.enabled=true
+      -Dspark.master.rest.port=6066
+      org.apache.spark.deploy.master.Master
     ports:
       - "8080:8080"
       - "7077:7077"
+      - "6066:6066"  # <= обязательно!
     volumes:
       - ./spark_jobs:/opt/bitnami/spark/jobs
       - ./data:/opt/bitnami/spark/data
     depends_on:
       data-downloader:
         condition: service_completed_successfully
+    environment:
+      SPARK_MASTER_HOST: spark-master
+      SPARK_MASTER_PORT: 7077
+      SPARK_MASTER_WEBUI_PORT: 8080
+      SPARK_MASTER_REST_PORT: 6066
+    networks:
+      - bigdata
 
   spark-worker:
     build:
@@ -50,6 +67,8 @@ services:
         condition: service_completed_successfully
       spark-master:
         condition: service_started
+    networks:
+      - bigdata
 
   minio:
     image: minio/minio
@@ -65,6 +84,8 @@ services:
     depends_on:
       data-downloader:
         condition: service_completed_successfully
+    networks:
+      - bigdata
 
   postgres:
     image: postgres:13
@@ -79,27 +100,66 @@ services:
       interval: 5s
       timeout: 5s
       retries: 5
+    networks:
+      - bigdata
 
-  prefect-server:
-    build: ./prefect
+  prefect-migrate:
+    build:
+      context: ./prefect
+      dockerfile: Dockerfile
     command: >
       bash -c "
-        prefect server start --host 0.0.0.0 &
-        prefect deployment build /opt/prefect/flows/etl_flow.py:big_data_etl_flow -n 'Big Data ETL' --apply
-        prefect agent start -q 'default'
+        echo 'Upgrading database...' &&
+        prefect server database upgrade --yes &&
+        echo 'Database migration complete.' &&
+        echo 'Creating/Updating deployment...' &&
+        prefect work-pool create --type process spark-pool &&
+        prefect deployment build /opt/prefect/flows/etl_flow.py:big_data_etl_flow -n 'Big Data ETL' --pool spark-pool --apply
       "
+    environment:
+      PREFECT_API_DATABASE_CONNECTION_URL: "postgresql+asyncpg://user:password@postgres:5432/project_db"
+    volumes:
+      - ./flows:/opt/prefect/flows
+    depends_on:
+      postgres:
+        condition: service_healthy
+    networks:
+      - bigdata
+
+  prefect-server:
+    build:
+      context: ./prefect
+      dockerfile: Dockerfile
+    # Команда теперь находится в entrypoint.sh
+    command: prefect server start --host 0.0.0.0
+    restart: unless-stopped
     ports:
       - "9090:4200"
+    environment:
+      PREFECT_API_DATABASE_CONNECTION_URL: "postgresql+asyncpg://user:password@postgres:5432/project_db"
+      PREFECT_API_URL: "http://prefect-server:4200/api"
+    depends_on:
+      prefect-migrate:
+        condition: service_completed_successfully
+    networks:
+      - bigdata
+
+  prefect-worker:
+    build:
+      context: ./prefect
+      dockerfile: Dockerfile
+    command: prefect worker start -p spark-pool
+    restart: unless-stopped
     volumes:
       - ./flows:/opt/prefect/flows
       - ./data:/data
     environment:
-      PREFECT_API_DATABASE_CONNECTION_URL: "postgresql+asyncpg://user:password@postgres:5432/project_db"
+      PREFECT_API_URL: "http://prefect-server:4200/api"
     depends_on:
-      data-downloader:
-        condition: service_completed_successfully
-      postgres:
-        condition: service_healthy # <-- Ждем, пока БД будет "здорова"
+      prefect-server:
+        condition: service_started
+    networks:
+      - bigdata
 
   grafana:
     image: grafana/grafana-oss:latest
@@ -107,3 +167,5 @@ services:
       - "3000:3000"
     depends_on:
       - postgres # <-- Добавлена простая зависимость, чтобы Grafana стартовала после БД
+    networks:
+      - bigdata
